package org.papaja.adminfly.commons.geo;

@SuppressWarnings({"SpellCheckingInspection"})
public enum Country {

    AF("AFGHANISTAN", "افغانستان", "AF"),
    AL("ALBANIA", "Shqipëria", "AL"),
    DZ("ALGERIA", "ⴷⵣⴰⵢⴻⵔ", "DZ"),
    AS("AMERICAN SAMOA", "Amerika Sāmoa", "AS"),
    AD("ANDORRA", "Andorra", "AD"),
    AO("ANGOLA", "Ngola", "AO"),
    AQ("ANTARCTICA", "ANTARCTICA", "AQ"),
    AG("ANTIGUA AND BARBUDA", "Antigua and Barbuda", "AG"),
    AR("ARGENTINA", "Argentina", "AR"),
    AM("ARMENIA", "Հայաստան", "AM"),
    AW("ARUBA", "Aruba", "AW"),
    AU("AUSTRALIA", "Australia", "AU"),
    AT("AUSTRIA", "Österreich", "AT"),
    AZ("AZERBAIJAN", "Azərbaycan", "AZ"),
    BS("BAHAMAS", "Bahamas", "BS"),
    BH("BAHRAIN", "البحرين", "BH"),
    BD("BANGLADESH", "বাংলাদেশ", "BD"),
    BB("BARBADOS", "Barbados", "BB"),
    BY("BELARUS", "Беларусь", "BY"),
    BE("BELGIUM", "Belgique", "BE"),
    BZ("BELIZE", "Belize", "BZ"),
    BJ("BENIN", "Bénin", "BJ"),
    BM("BERMUDA", "Bermuda", "BM"),
    BT("BHUTAN", "འབྲུག་ཡུལ", "BT"),
    BO("BOLIVIA", "Buliwya", "BO"),
    BA("BOSNIA AND HERZEGOVINA", "", "BA"),
    BW("BOTSWANA", "Босна и Херцеговина", "BW"),
    BR("BRAZIL", "Brasil", "BR"),
    BN("BRUNEI", "بروني", "BN"),
    BG("BULGARIA", "България", "BG"),
    BF("BURKINA FASO", "Burkina Faso", "BF"),
    BI("BURUNDI", "Uburundi", "BI"),
    KH("CAMBODIA", "កម្ពុជា", "KH"),
    CM("CAMEROON", "Cameroon", "CM"),
    CA("CANADA", "Canada", "CA"),
    CV("CAPE VERDE", "Cabo Verde", "CV"),
    KY("CAYMAN ISLANDS", "Cayman Islands", "KY"),
    CF("CENTRAL AFRICAN REPUBLIC", "Ködörösêse tî Bêafrîka", "CF"),
    TD("CHAD", "تشاد", "TD"),
    CL("CHILE", "Chile", "CL"),
    CN("CHINA", "中国", "CN"),
    CX("CHRISTMAS ISLAND", "Christmas Island", "CX"),
    CC("COCOS (KEELING) ISLANDS", "Cocos Islands", "CC"),
    CO("COLOMBIA", "Colombia", "CO"),
    KM("COMOROS", "جزر القمر", "KM"),
    CG("CONGO", "Republíki ya Kongó", "CG"),
    CK("COOK ISLANDS", "Cook Islands", "CK"),
    CR("COSTA RICA", "Costa Rica", "CR"),
    CI("CÔTE D'IVOIRE", "Côte d'Ivoire", "CI"),
    HR("CROATIA", "Hrvatska", "HR"),
    CU("CUBA", "Cuba", "CU"),
    CY("CYPRUS", "Κύπρος", "CY"),
    CZ("CZECH REPUBLIC", "Česká republika", "CZ"),
    DK("DENMARK", "Danmark", "DK"),
    DJ("DJIBOUTI", "جيبوتي", "DJ"),
    DM("DOMINICA", "Dominica", "DM"),
    DO("DOMINICAN REPUBLIC", "República Dominicana", "DO"),
    EC("ECUADOR", "Ecuador", "EC"),
    EG("Egypt", "مصر", "EG"),
    SV("El Salvador", "El Salvador", "SV"),
    GQ("Equatorial Guinea", "Guinea Ecuatorial", "GQ"),
    ER("Eritrea", "ኤርትራ", "ER"),
    EE("Estonia", "Eesti", "EE"),
    ET("Ethiopia", "ኢትዮጵያ", "ET"),
    FK("Falkland Islands", "Falkland Islands", "FK"),
    FO("Faroe Islands", "Føroyar", "FO"),
    FJ("Fiji", "Viti", "FJ"),
    FI("Finland", "Suomi", "FI"),
    FR("France", "France", "FR"),
    GF("French Guiana", "Guyane", "GF"),
    PF("French Polynesia", "Polynésie française", "PF"),
    GA("Gabon", "République gabonaise", "GA"),
    GM("The Gambia", "The Gambia", "GM"),
    GE("Georgia", "საქართველო", "GE"),
    DE("Germany", "Deutschland", "DE"),
    GH("Ghana", "Gaana", "GH"),
    GI("Gibraltar", "Gibraltar", "GI"),
    GR("Greece", "Ελλάδα", "GR"),
    GL("Greenland", "Kalaallit Nunaat", "GL"),
    GD("Grenada", "Grenada", "GD"),
    GP("Guadeloupe", "Guadeloupe", "GP"),
    GU("Guam", "Guåhån", "GU"),
    GT("Guatemala", "Guatemala", "GT"),
    GN("Guinea", "Gine", "GN"),
    GW("Guinea-Bissau", "Guiné-Bissau", "GW"),
    GY("Guyana", "Guyana", "GY"),
    HT("Haiti", "Ayiti", "HT"),
    HN("Honduras", "Honduras", "HN"),
    HK("Hong Kong", "香港", "HK"),
    HU("Hungary", "Magyarország", "HU"),
    IS("Iceland", "Ísland", "IS"),
    IN("India", "भारत", "IN"),
    ID("Indonesia", "Indonesia", "ID"),
    IR("Iran", "ایران", "IR"),
    IQ("Iraq", "العراق", "IQ"),
    IE("Ireland", "Ireland", "IE"),
    IL("Israel", "ישראל", "IL"),
    IT("Italy", "Italia", "IT"),
    JM("Jamaica", "Jamaica", "JM"),
    JP("Japan", "日本", "JP"),
    JO("Jordan", "الأردن", "JO"),
    KZ("Kazakhstan", "Қазақстан", "KZ"),
    KE("Kenya", "Kenya", "KE"),
    KI("Kiribati", "Kiribati", "KI"),
    KP("North Korea", "朝鮮", "KP"),
    KR("South Korea", "한국", "KR"),
    KW("Kuwait", "الكويت", "KW"),
    KG("Kyrgyzstan", "Кыргызстан", "KG"),
    LA("Laos", "ປະເທດລາວ", "LA"),
    LV("Latvia", "Latvija", "LV"),
    LB("Lebanon", "لبنان", "LB"),
    LS("Lesotho", "Lesotho", "LS"),
    LR("Liberia", "Liberia", "LR"),
    LI("Liechtenstein", "Liechtenstein", "LI"),
    LT("Lithuania", "Lietuva", "LT"),
    LY("Libya", "ليبيا", "LT"),
    LU("Luxembourg", "Lëtzebuerg", "LU"),
    MO("Macau", "澳門", "MO"),
    MK("Macedonia", "Северна Македонија", "MK"),
    MG("Madagascar", "Madagasikara", "MG"),
    MW("Malawi", "Malaŵi", "MW"),
    MY("Malaysia", "马来西亚", "MY"),
    MV("Maldives", "ދިވެހިރާއްޖެ", "MV"),
    ML("Mali", "Mali", "ML"),
    MT("Malta", "Malta", "MT"),
    MH("Marshall Islands", "Aorōkin M̧ajeļ", "MH"),
    MQ("Martinique", "Martinique", "MQ"),
    MR("Mauritania", "موريتانيا", "MR"),
    MU("Mauritius", "Moris", "MU"),
    YT("Mayotte", "Mayotte", "YT"),
    MX("Mexico", "México", "MX"),
    FM("Federated States of Micronesia", "Federated States of Micronesia", "FM"),
    MD("Moldova", "Moldova", "MD"),
    MC("Monaco", "Monaco", "MC"),
    MN("Mongolia", "Монгол Улс", "MN"),
    ME("Montenegro", "Црна Гора", "ME"),
    MS("Montserrat", "Montserrat", "MS"),
    MA("Morocco", "المغرب", "MA"),
    MZ("Mozambique", "Moçambique", "MZ"),
    MM("Myanmar", "မြန်မာ", "MM"),
    NA("Namibia", "Namibia", "NA"),
    NR("Nauru", "Naoero", "NR"),
    NP("Nepal", "नेपाल", "NP"),
    NL("Netherlands", "Nederland", "NL"),
    NC("New Caledonia", "Nouvelle-Calédonie", "NC"),
    NZ("New Zealand", "New Zealand", "NZ"),
    NI("Nicaragua", "Nicaragua", "NI"),
    NE("Niger", "Niger", "NE"),
    NG("Nigeria", "Nàìjíríà", "NG"),
    NU("Niue", "Niuē", "NU"),
    NF("Norfolk Island", "Norf'k Ailen", "NF"),
    NO("Norway", "Norge", "NO"),
    OM("Oman", "عُمان", "OM"),
    PK("Pakistan", "پاکستان", "PK"),
    PW("Palau", "Belau", "PW"),
    PS("Palestine", "فلسطين", "PS"),
    PA("Panama", "Panamá", "PA"),
    PG("Papua New Guinea", "Papua New Guinea", "PG"),
    PY("Paraguay", "Paraguay", "PY"),
    PE("Peru", "Perú", "PE"),
    PH("Philippines", "Pilipinas", "PH"),
    PL("Poland", "Polska", "PL"),
    PT("Portugal", "Portugal", "PT"),
    PR("Puerto Rico", "Puerto Rico", "PR"),
    QA("Qatar", "قطر", "QA"),
    RE("RÉUNION", "", "RE"),
    RO("ROMANIA", "", "RO"),
    RU("RUSSIAN FEDERATION", "", "RU"),
    RW("RWANDA", "", "RW"),
    SH("SAINT HELENA", "", "SH"),
    KN("SAINT KITTS AND NEVIS", "", "KN"),
    LC("SAINT LUCIA", "", "LC"),
    PM("SAINT PIERRE AND MIQUELON", "", "PM"),
    VC("SAINT VINCENT AND THE GRENADINES", "", "VC"),
    WS("SAMOA", "", "WS"),
    SM("SAN MARINO", "", "SM"),
    ST("SAO TOME AND PRINCIPE", "", "ST"),
    SA("SAUDI ARABIA", "", "SA"),
    SN("SENEGAL", "", "SN"),
    RS("SERBIA", "", "RS"),
    SC("SEYCHELLES", "", "SC"),
    SL("SIERRA LEONE", "", "SL"),
    SG("SINGAPORE", "", "SG"),
    SK("SLOVAKIA", "", "SK"),
    SI("SLOVENIA", "", "SI"),
    SB("SOLOMON ISLANDS", "", "SB"),
    SO("SOMALIA", "", "SO"),
    ZA("SOUTH AFRICA", "", "ZA"),
    GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "", "GS"),
    ES("SPAIN", "", "ES"),
    LK("SRI LANKA", "", "LK"),
    SD("SUDAN", "", "SD"),
    SR("SURINAME", "", "SR"),
    SJ("SVALBARD AND JAN MAYEN", "", "SJ"),
    SZ("SWAZILAND", "", "SZ"),
    SE("SWEDEN", "", "SE"),
    CH("SWITZERLAND", "", "CH"),
    SY("SYRIAN ARAB REPUBLIC", "", "SY"),
    TW("TAIWAN", "", "TW"),
    TJ("TAJIKISTAN", "", "TJ"),
    TZ("TANZANIA", "", "TZ"),
    TH("THAILAND", "", "TH"),
    TL("TIMOR-LESTE", "", "TL"),
    TG("TOGO", "", "TG"),
    TK("TOKELAU", "", "TK"),
    TO("TONGA", "", "TO"),
    TT("TRINIDAD AND TOBAGO", "", "TT"),
    TN("TUNISIA", "", "TN"),
    TR("TURKEY", "", "TR"),
    TM("TURKMENISTAN", "", "TM"),
    TC("TURKS AND CAICOS ISLANDS", "", "TC"),
    TV("TUVALU", "", "TV"),
    UG("UGANDA", "", "UG"),
    UA("UKRAINE", "", "UA"),
    AE("UNITED ARAB EMIRATES", "", "AE"),
    GB("UNITED KINGDOM", "", "GB"),
    US("UNITED STATES", "", "US"),
    UM("UNITED STATES MINOR OUTLYING ISLANDS", "", "UM"),
    UY("URUGUAY", "", "UY"),
    UZ("UZBEKISTAN", "", "UZ"),
    VU("VANUATU", "", "VU"),
    VE("VENEZUELA", "", "VE"),
    VN("VIET NAM", "", "VN"),
    VG("VIRGIN ISLANDS, BRITISH", "", "VG"),
    VI("VIRGIN ISLANDS, U.S.", "", "VI"),
    WF("WALLIS AND FUTUNA", "", "WF"),
    EH("WESTERN SAHARA", "", "EH"),
    YE("YEMEN", "", "YE"),
    ZM("ZAMBIA", "", "ZM"),
    ZW("ZIMBABWE", "", "ZW");

    private String name;
    private String local;
    private String code;

    Country(String name, String local, String code) {
        this.name = name;
        this.local = local;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getLocal() {
        return local;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return String.format("Country{name='%s', code='%s'}", name, code);
    }
}
