package org.papaja.adminfly.commons.geo;

@SuppressWarnings({"SpellCheckingInspection"})
public enum Country {

    AF("AFGHANISTAN", "افغانستان", "AF"),
    AL("ALBANIA", "Shqipëria", "AL"),
    DZ("ALGERIA", "ⴷⵣⴰⵢⴻⵔ", "DZ"),
    AS("AMERICAN SAMOA", "Amerika Sāmoa", "AS"),
    AD("ANDORRA", "Andorra", "AD"),
    AO("ANGOLA", "Ngola", "AO"),
    AQ("ANTARCTICA", "ANTARCTICA", "AQ"),
    AG("ANTIGUA AND BARBUDA", "Antigua and Barbuda", "AG"),
    AR("ARGENTINA", "Argentina", "AR"),
    AM("ARMENIA", "Հայաստան", "AM"),
    AW("ARUBA", "Aruba", "AW"),
    AU("AUSTRALIA", "Australia", "AU"),
    AT("AUSTRIA", "Österreich", "AT"),
    AZ("AZERBAIJAN", "Azərbaycan", "AZ"),
    BS("BAHAMAS", "Bahamas", "BS"),
    BH("BAHRAIN", "البحرين", "BH"),
    BD("BANGLADESH", "বাংলাদেশ", "BD"),
    BB("BARBADOS", "Barbados", "BB"),
    BY("BELARUS", "Беларусь", "BY"),
    BE("BELGIUM", "Belgique", "BE"),
    BZ("BELIZE", "Belize", "BZ"),
    BJ("BENIN", "Bénin", "BJ"),
    BM("BERMUDA", "Bermuda", "BM"),
    BT("BHUTAN", "འབྲུག་ཡུལ", "BT"),
    BO("BOLIVIA", "Buliwya", "BO"),
    BA("BOSNIA AND HERZEGOVINA", "", "BA"),
    BW("BOTSWANA", "Босна и Херцеговина", "BW"),
    BR("BRAZIL", "Brasil", "BR"),
    BN("BRUNEI", "بروني", "BN"),
    BG("BULGARIA", "България", "BG"),
    BF("BURKINA FASO", "Burkina Faso", "BF"),
    BI("BURUNDI", "Uburundi", "BI"),
    KH("CAMBODIA", "កម្ពុជា", "KH"),
    CM("CAMEROON", "Cameroon", "CM"),
    CA("CANADA", "Canada", "CA"),
    CV("CAPE VERDE", "Cabo Verde", "CV"),
    KY("CAYMAN ISLANDS", "Cayman Islands", "KY"),
    CF("CENTRAL AFRICAN REPUBLIC", "Ködörösêse tî Bêafrîka", "CF"),
    TD("CHAD", "تشاد", "TD"),
    CL("CHILE", "Chile", "CL"),
    CN("CHINA", "中国", "CN"),
    CX("CHRISTMAS ISLAND", "Christmas Island", "CX"),
    CC("COCOS (KEELING) ISLANDS", "Cocos Islands", "CC"),
    CO("COLOMBIA", "Colombia", "CO"),
    KM("COMOROS", "جزر القمر", "KM"),
    CG("CONGO", "Republíki ya Kongó", "CG"),
    CK("COOK ISLANDS", "Cook Islands", "CK"),
    CR("COSTA RICA", "Costa Rica", "CR"),
    CI("CÔTE D'IVOIRE", "Côte d'Ivoire", "CI"),
    HR("CROATIA", "Hrvatska", "HR"),
    CU("CUBA", "Cuba", "CU"),
    CY("CYPRUS", "Κύπρος", "CY"),
    CZ("CZECH REPUBLIC", "Česká republika", "CZ"),
    DK("DENMARK", "Danmark", "DK"),
    DJ("DJIBOUTI", "جيبوتي", "DJ"),
    DM("DOMINICA", "", "DM"),
    DO("DOMINICAN REPUBLIC", "", "DO"),
    EC("ECUADOR", "", "EC"),
    EG("EGYPT", "", "EG"),
    SV("EL SALVADOR", "", "SV"),
    GQ("EQUATORIAL GUINEA", "", "GQ"),
    ER("ERITREA", "", "ER"),
    EE("ESTONIA", "", "EE"),
    ET("ETHIOPIA", "", "ET"),
    FK("FALKLAND ISLANDS (MALVINAS)", "", "FK"),
    FO("FAROE ISLANDS", "", "FO"),
    FJ("FIJI", "", "FJ"),
    FI("FINLAND", "", "FI"),
    FR("FRANCE", "", "FR"),
    GF("FRENCH GUIANA", "", "GF"),
    PF("FRENCH POLYNESIA", "", "PF"),
    TF("FRENCH SOUTHERN TERRITORIES", "", "TF"),
    GA("GABON", "", "GA"),
    GM("GAMBIA", "", "GM"),
    GE("GEORGIA", "", "GE"),
    DE("GERMANY", "", "DE"),
    GH("GHANA", "", "GH"),
    GI("GIBRALTAR", "", "GI"),
    GR("GREECE", "", "GR"),
    GL("GREENLAND", "", "GL"),
    GD("GRENADA", "", "GD"),
    GP("GUADELOUPE", "", "GP"),
    GU("GUAM", "", "GU"),
    GT("GUATEMALA", "", "GT"),
    GN("GUINEA", "", "GN"),
    GW("GUINEA-BISSAU", "", "GW"),
    GY("GUYANA", "", "GY"),
    HT("HAITI", "", "HT"),
    HM("HEARD ISLAND AND MCDONALD ISLANDS", "", "HM"),
    HN("HONDURAS", "", "HN"),
    HK("HONG KONG", "", "HK"),
    HU("HUNGARY", "", "HU"),
    IS("ICELAND", "", "IS"),
    IN("INDIA", "", "IN"),
    ID("INDONESIA", "", "ID"),
    IR("IRAN", "", "IR"),
    IQ("IRAQ", "", "IQ"),
    IE("IRELAND", "", "IE"),
    IL("ISRAEL", "", "IL"),
    IT("ITALY", "", "IT"),
    JM("JAMAICA", "", "JM"),
    JP("JAPAN", "", "JP"),
    JO("JORDAN", "", "JO"),
    KZ("KAZAKHSTAN", "", "KZ"),
    KE("KENYA", "", "KE"),
    KI("KIRIBATI", "", "KI"),
    KP("NORTH KOREA", "", "KP"),
    KR("SOUTH KOREA", "", "KR"),
    KW("KUWAIT", "", "KW"),
    KG("KYRGYZSTAN", "", "KG"),
    LA("LAOS", "", "LA"),
    LV("LATVIA", "", "LV"),
    LB("LEBANON", "", "LB"),
    LS("LESOTHO", "", "LS"),
    LR("LIBERIA", "", "LR"),
    LY("LIBYAN ARAB JAMAHIRIYA", "", "LY"),
    LI("LIECHTENSTEIN", "", "LI"),
    LT("LITHUANIA", "", "LT"),
    LU("LUXEMBOURG", "", "LU"),
    MO("MACAO", "", "MO"),
    MK("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "", "MK"),
    MG("MADAGASCAR", "", "MG"),
    MW("MALAWI", "", "MW"),
    MY("MALAYSIA", "", "MY"),
    MV("MALDIVES", "", "MV"),
    ML("MALI", "", "ML"),
    MT("MALTA", "", "MT"),
    MH("MARSHALL ISLANDS", "", "MH"),
    MQ("MARTINIQUE", "", "MQ"),
    MR("MAURITANIA", "", "MR"),
    MU("MAURITIUS", "", "MU"),
    YT("MAYOTTE", "", "YT"),
    MX("MEXICO", "", "MX"),
    FM("MICRONESIA, FEDERATED STATES OF", "", "FM"),
    MD("MOLDOVA, REPUBLIC OF", "", "MD"),
    MC("MONACO", "", "MC"),
    MN("MONGOLIA", "", "MN"),
    ME("MONTENEGRO", "", "ME"),
    MS("MONTSERRAT", "", "MS"),
    MA("MOROCCO", "", "MA"),
    MZ("MOZAMBIQUE", "", "MZ"),
    MM("MYANMAR", "", "MM"),
    NA("NAMIBIA", "", "NA"),
    NR("NAURU", "", "NR"),
    NP("NEPAL", "", "NP"),
    NL("NETHERLANDS", "", "NL"),
    AN("NETHERLANDS ANTILLES", "", "AN"),
    NC("NEW CALEDONIA", "", "NC"),
    NZ("NEW ZEALAND", "", "NZ"),
    NI("NICARAGUA", "", "NI"),
    NE("NIGER", "", "NE"),
    NG("NIGERIA", "", "NG"),
    NU("NIUE", "", "NU"),
    NF("NORFOLK ISLAND", "", "NF"),
    MP("NORTHERN MARIANA ISLANDS", "", "MP"),
    NO("NORWAY", "", "NO"),
    OM("OMAN", "", "OM"),
    PK("PAKISTAN", "", "PK"),
    PW("PALAU", "", "PW"),
    PS("PALESTINIAN TERRITORY, OCCUPIED", "", "PS"),
    PA("PANAMA", "", "PA"),
    PG("PAPUA NEW GUINEA", "", "PG"),
    PY("PARAGUAY", "", "PY"),
    PE("PERU", "", "PE"),
    PH("PHILIPPINES", "", "PH"),
    PN("PITCAIRN", "", "PN"),
    PL("POLAND", "", "PL"),
    PT("PORTUGAL", "", "PT"),
    PR("PUERTO RICO", "", "PR"),
    QA("QATAR", "", "QA"),
    RE("RÉUNION", "", "RE"),
    RO("ROMANIA", "", "RO"),
    RU("RUSSIAN FEDERATION", "", "RU"),
    RW("RWANDA", "", "RW"),
    SH("SAINT HELENA", "", "SH"),
    KN("SAINT KITTS AND NEVIS", "", "KN"),
    LC("SAINT LUCIA", "", "LC"),
    PM("SAINT PIERRE AND MIQUELON", "", "PM"),
    VC("SAINT VINCENT AND THE GRENADINES", "", "VC"),
    WS("SAMOA", "", "WS"),
    SM("SAN MARINO", "", "SM"),
    ST("SAO TOME AND PRINCIPE", "", "ST"),
    SA("SAUDI ARABIA", "", "SA"),
    SN("SENEGAL", "", "SN"),
    RS("SERBIA", "", "RS"),
    SC("SEYCHELLES", "", "SC"),
    SL("SIERRA LEONE", "", "SL"),
    SG("SINGAPORE", "", "SG"),
    SK("SLOVAKIA", "", "SK"),
    SI("SLOVENIA", "", "SI"),
    SB("SOLOMON ISLANDS", "", "SB"),
    SO("SOMALIA", "", "SO"),
    ZA("SOUTH AFRICA", "", "ZA"),
    GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "", "GS"),
    ES("SPAIN", "", "ES"),
    LK("SRI LANKA", "", "LK"),
    SD("SUDAN", "", "SD"),
    SR("SURINAME", "", "SR"),
    SJ("SVALBARD AND JAN MAYEN", "", "SJ"),
    SZ("SWAZILAND", "", "SZ"),
    SE("SWEDEN", "", "SE"),
    CH("SWITZERLAND", "", "CH"),
    SY("SYRIAN ARAB REPUBLIC", "", "SY"),
    TW("TAIWAN", "", "TW"),
    TJ("TAJIKISTAN", "", "TJ"),
    TZ("TANZANIA", "", "TZ"),
    TH("THAILAND", "", "TH"),
    TL("TIMOR-LESTE", "", "TL"),
    TG("TOGO", "", "TG"),
    TK("TOKELAU", "", "TK"),
    TO("TONGA", "", "TO"),
    TT("TRINIDAD AND TOBAGO", "", "TT"),
    TN("TUNISIA", "", "TN"),
    TR("TURKEY", "", "TR"),
    TM("TURKMENISTAN", "", "TM"),
    TC("TURKS AND CAICOS ISLANDS", "", "TC"),
    TV("TUVALU", "", "TV"),
    UG("UGANDA", "", "UG"),
    UA("UKRAINE", "", "UA"),
    AE("UNITED ARAB EMIRATES", "", "AE"),
    GB("UNITED KINGDOM", "", "GB"),
    US("UNITED STATES", "", "US"),
    UM("UNITED STATES MINOR OUTLYING ISLANDS", "", "UM"),
    UY("URUGUAY", "", "UY"),
    UZ("UZBEKISTAN", "", "UZ"),
    VU("VANUATU", "", "VU"),
    VE("VENEZUELA", "", "VE"),
    VN("VIET NAM", "", "VN"),
    VG("VIRGIN ISLANDS, BRITISH", "", "VG"),
    VI("VIRGIN ISLANDS, U.S.", "", "VI"),
    WF("WALLIS AND FUTUNA", "", "WF"),
    EH("WESTERN SAHARA", "", "EH"),
    YE("YEMEN", "", "YE"),
    ZM("ZAMBIA", "", "ZM"),
    ZW("ZIMBABWE", "", "ZW");

    private String name;
    private String local;
    private String code;

    Country(String name, String local, String code) {
        this.name = name;
        this.local = local;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getLocal() {
        return local;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return String.format("Country{name='%s', code='%s'}", name, code);
    }
}
