package org.papaja.adminfly.commons.geo;

public enum LanguageOld {

    AB("Abkhazian", "AB"),
    AA("Afar", "AA"),
    AF("Afrikaans", "AF"),
    AK("Akan", "AK"),
    SQ("Albanian", "SQ"),
    AM("Amharic", "አማርኛ", "AM"),
    AR("Arabic", "AR"),
    AN("Aragonese", "AN"),
    HY("Armenian", "HY"),
    AS("Assamese", "AS"),
    AV("Avaric", "AV"),
    AE("Avestan", "AE"),
    AY("Aymara", "AY"),
    AZ("Azerbaijani", "AZ"),
    BM("Bambara", "BM"),
    BA("Bashkir", "BA"),
    EU("Basque", "EU"),
    BE("Belarusian", "Беларуская", "BE"),
    BN("Bengali", "বাঙালি", "BN"),
    BH("Bihari", "BH"),
    BI("Bislama", "BI"),
    BS("Bosnian", "BS"),
    BR("Breton", "BR"),
    BG("Bulgarian", "BG"),
    MY("Burmese", "မြန်မာ", "MY"),
    CA("Catalan", "CA"),
    CH("Chamorro", "CH"),
    CE("Chechen", "CE"),
    NY("Chichewa, Chewa, Nyanja", "NY"),
    ZH("Chinese", "中文", "ZH"),
    ZH_HANS("Chinese (Simplified)", "ZH_HANS"),
    ZH_HANT("Chinese (Traditional)", "ZH_HANT"),
    CV("Chuvash", "CV"),
    KW("Cornish", "KW"),
    CO("Corsican", "CO"),
    CR("Cree", "CR"),
    HR("Croatian", "HR"),
    CS("Czech", "CS"),
    DA("Danish", "DA"),
    DV("Divehi, Dhivehi, Maldivian", "DV"),
    NL("Dutch", "NL"),
    DZ("Dzongkha", "DZ"),
    EN("English", "English", "EN"),
    EO("Esperanto", "EO"),
    ET("Estonian", "ET"),
    EE("Ewe", "EE"),
    FO("Faroese", "FO"),
    FJ("Fijian", "FJ"),
    FI("Finnish", "FI"),
    FR("French", "Française", "FR"),
    FF("Fula, Fulah, Pulaar, Pular", "FF"),
    GL("Galician", "GL"),
    GD("Gaelic (Scottish)", "GD"),
    GV("Gaelic (Manx)", "GV"),
    KA("Georgian", "ქართული", "KA"),
    DE("German", "Deutsche", "DE"),
    EL("Greek", "Ελληνικά", "EL"),
    KL("Greenlandic", "KL"),
    GN("Guarani", "GN"),
    GU("Gujarati", "GU"),
    HT("Haitian Creole", "HT"),
    HA("Hausa", "HA"),
    HE("Hebrew", "HE"),
    HZ("Herero", "HZ"),
    HI("Hindi", "हिंदी", "HI"),
    HO("Hiri Motu", "HO"),
    HU("Hungarian", "HU"),
    IS("Icelandic", "IS"),
    IO("Ido", "IO"),
    IG("Igbo", "IG"),
    IN("Indonesian", "Bahasa Indonesia", "IN"),
    IA("Interlingua", "IA"),
    IE("Interlingue", "IE"),
    IU("Inuktitut", "IU"),
    IK("Inupiak", "IK"),
    GA("Irish", "GA"),
    IT("Italian", "IT"),
    JA("Japanese", "日本人", "JA"),
    JV("Javanese", "JV"),
    KN("Kannada", "KN"),
    KR("Kanuri", "KR"),
    KS("Kashmiri", "KS"),
    KK("Kazakh", "KK"),
    KM("Khmer", "ភាសាខ្មែរ", "KM"),
    KI("Kikuyu", "KI"),
    RW("Kinyarwanda (Rwanda)", "RW"),
    RN("Kirundi", "RN"),
    KY("Kyrgyz", "KY"),
    KV("Komi", "KV"),
    KG("Kongo", "KG"),
    KO("Korean", "한국어", "KO"),
    KU("Kurdish", "KU"),
    KJ("Kwanyama", "KJ"),
    LO("Lao", "ລາວ", "LO"),
    LA("Latin", "LA"),
    LV("Latvian (Lettish)", "LV"),
    LI("Limburgish ( Limburger)", "LI"),
    LN("Lingala", "LN"),
    LT("Lithuanian", "LT"),
    LU("Luga-Katanga", "LU"),
    LG("Luganda, Ganda", "LG"),
    LB("Luxembourgish", "LB"),
    MK("Macedonian", "MK"),
    MG("Malagasy", "MG"),
    MS("Malay", "MS"),
    ML("Malayalam", "ML"),
    MT("Maltese", "MT"),
    MI("Maori", "MI"),
    MR("Marathi", "MR"),
    MH("Marshallese", "MH"),
    MO("Moldavian", "MO"),
    MN("Mongolian", "MN"),
    NA("Nauru", "NA"),
    NV("Navajo", "NV"),
    NG("Ndonga", "NG"),
    ND("Northern Ndebele", "ND"),
    NE("Nepali", "NE"),
    NO("Norwegian", "Norsk", "NO"),
    NB("Norwegian bokmål", "NB"),
    NN("Norwegian nynorsk", "NN"),
    II("Nuosu", "II"),
    OC("Occitan", "OC"),
    OJ("Ojibwe", "OJ"),
    CU("Old Church Slavonic, Old Bulgarian", "CU"),
    OR("Oriya", "OR"),
    OM("Oromo (Afaan Oromo)", "OM"),
    OS("Ossetian", "OS"),
    PI("Pāli", "PI"),
    PS("Pashto, Pushto", "PS"),
    FA("Persian (Farsi)", "FA"),
    PL("Polish", "Polskie", "PL"),
    PT("Portuguese", "Português", "PT"),
    PA("Punjabi (Eastern)", "PA"),
    QU("Quechua", "QU"),
    RM("Romansh", "RM"),
    RO("Romanian", "RO"),
    RU("Russian", "Русский", "RU"),
    SE("Sami", "SE"),
    SM("Samoan", "SM"),
    SG("Sango", "SG"),
    SA("Sanskrit", "SA"),
    SR("Serbian", "SR"),
    SH("Serbo-Croatian", "SH"),
    ST("Sesotho", "ST"),
    TN("Setswana", "TN"),
    SN("Shona", "SN"),
    SD("Sindhi", "SD"),
    SI("Sinhalese", "SI"),
    SS("Siswati", "SS"),
    SK("Slovak", "SK"),
    SL("Slovenian", "SL"),
    SO("Somali", "SO"),
    NR("Southern Ndebele", "NR"),
    ES("Spanish", "Española", "ES"),
    SU("Sundanese", "SU"),
    SW("Swahili (Kiswahili)", "SW"),
    SV("Swedish", "SV"),
    TL("Tagalog", "TL"),
    TY("Tahitian", "TY"),
    TG("Tajik", "TG"),
    TA("Tamil", "TA"),
    TT("Tatar", "TT"),
    TE("Telugu", "TE"),
    TH("Thai", "ไทย", "TH"),
    BO("Tibetan", "BO"),
    TI("Tigrinya", "TI"),
    TO("Tonga", "TO"),
    TS("Tsonga", "TS"),
    TR("Turkish", "TR"),
    TK("Turkmen", "TK"),
    TW("Twi", "TW"),
    UG("Uyghur", "UG"),
    UK("Ukrainian", "Українська", "UK"),
    UR("Urdu", "UR"),
    UZ("Uzbek", "UZ"),
    VE("Venda", "VE"),
    VI("Vietnamese", "VI"),
    VO("Volapük", "VO"),
    WA("Wallon", "WA"),
    CY("Welsh", "CY"),
    WO("Wolof", "WO"),
    FY("Western Frisian", "FY"),
    XH("Xhosa", "XH"),
    JI("Yiddish", "JI"),
    YO("Yoruba", "YO"),
    ZA("Zhuang, Chuang", "ZA"),
    ZU("Zulu", "ZU");

    private String name;
    private String local;
    private String code;

    LanguageOld(String name, String code) {
        this(name, null, code);
    }

    LanguageOld(String name, String local, String code) {
        this.name = name;
        this.local = local;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getLocal() {
        return local;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return String.format("LanguageOld{name='%s', code='%s'}", name, code);
    }
}
